name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Used for PR comments
          action: "upload"
          app_location: "."  # Your HTML files are at the root
          output_location: ""  # No build step needed for plain HTML
